### ISSUE TITLE
More meaningful support for building and handling library packages

### ISSUE THREAD

**Issue by martinpaljak** [martinpaljak/ant-javacard#20]

**Comment by promovicz** [comment]
I already use ant-javacard to build library projects.

My suggestion would be merging this pull request or something similar as a first step: GH-26.

With this patch the JAR generated by ant-javacard will contain both class files and the EXP and CAP.

For using these files ant-javacard would need to extract them because some tools (Sun/Oracle CAP verifier) require having the bare EXP files.

**Comment by promovicz** [comment]
Update: GH-26 got merged

Proposal: if an <import/> has a JAR attribute but no EXP attribute then ant-javacard should try to extract the EXP files from the JAR or directory pointed to be the JAR attribute.

(I might implement this)
