### ISSUE TITLE
Header.cap component does not include package name

### ISSUE THREAD

**Issue by cheburashka** [martinpaljak/ant-javacard#3]
When building a cap everything works fine with JCDK 3.0.3 that I'm testing but the generated Header.cap component does not include a name (The ```package_name_info``` from the CAP file format specification has length 0). I see the same behavior if I use the regular ant tools so probably it is related to the internal converter but I wonder if is worth trying to fix that in this project. If so, I can have a look if someone can provide some guidance where to look to fix that.

**Comment by martinpaljak** [comment]
Where and how does the issue mandate itself? It is a project without a package (default package). I understand that building works, but afterwards installation or using the cap with some other tool fails?

**Comment by cheburashka** [comment]
Is purely a cosmetic issue, the resulting cap installs with no issues and if anything, is only that a manual parser would not find a name to display. I would like to fix it just for completeness sake, but I have not seen any impact other than cosmetic.

**Comment by martinpaljak** [comment]
Okay. As ant-javacard is a simple wrapper for the original Oracle code, I don't believe there is a "properly fit" place for such a hack (or it would be justified to add it).

Otherwise two possible locations:
* Modification to the cap file: https://github.com/martinpaljak/ant-javacard/blob/master/src/pro/javacard/ant/JavaCard.java#L507
* Adding some parameter to the process: https://github.com/martinpaljak/ant-javacard/blob/master/src/pro/javacard/ant/JavaCard.java#L473

**Comment by martinpaljak** [comment]
As ant-javacard is a usability wrapper, I don't intend to fix non-blocking issues with the Oracle developer kits. Meaningful minimalistic patches that fix annoying issues are still welcome, but they must be patches, not bug reports. Thus closing this for now.
